import { StyleSheet } from 'react-native';
import { COLORS } from '../../constants/colors';

export const styles = StyleSheet.create({
  landscapeContainer: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#fff',
  },
  productLane: {
    width: '30%',
    borderRightWidth: 1,
    borderRightColor: '#f3f4f6',
    padding: 10,
  },
  billingLane: {
    width: '70%',
  },
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  billingSection: {
    flex: 1,
  },
  header: {
    padding: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 12,
  },
  title: {
    fontSize: 28,
    fontWeight: '800',
    color: '#4b5563',
  },
  customerName: {
    fontSize: 16,
    color: '#a855f7',
    marginBottom: 4,
  },
  salesmanInfo: {
    fontSize: 14,
    color: '#6b7280',
    fontFamily: 'Montserrat',
    marginBottom: 4,
  },
  headerRight: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  iconButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#7b1fa2',
    justifyContent: 'center',
    alignItems: 'center',
  },
  scanButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#7b1fa2',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    gap: 8,
    marginLeft: 4,
  },
  scanButtonText: {
    color: 'white',
    fontWeight: '600',
    fontSize: 12,
  },
  searchContainer: {
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  searchBar: {
    height: 48,
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 12,
    paddingHorizontal: 16,
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  placeholderText: {
    color: '#9ca3af',
  },
  listContent: {
    flexGrow: 1,
    paddingBottom: 250,
  },
  emptyContainer: {
    flex: 1,
    height: 300,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyText: {
    marginTop: 16,
    fontSize: 16,
    color: '#9ca3af',
  },
  operationFooter: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#f3f4f6',
    padding: 16,
    zIndex: 10,
  },
  summaryGrid: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  summaryItem: {
    flex: 1,
  },
  summaryLabel: {
    fontSize: 14,
    color: '#6b7280',
    marginBottom: 4,
  },
  summaryValuePrimary: {
    fontSize: 24,
    fontWeight: '800',
    color: '#0288d1',
  },
  summaryValueSecondary: {
    fontSize: 22,
    fontWeight: '700',
    color: '#10b981',
  },
  summaryValueTertiary: {
    fontSize: 20,
    fontWeight: '600',
    color: '#9ca3af',
  },
  actionButtons: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  moreButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  actionBtn: {
    flex: 1,
    height: 50,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnText: {
    color: 'white',
    fontWeight: '700',
    fontSize: 14,
  },
  cashButton: {
    flex: 2,
    height: 50,
    backgroundColor: '#7b1fa2',
    borderRadius: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  cashLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  cashText: {
    color: 'white',
    fontSize: 20,
    fontWeight: '700',
  },
  cashAmount: {
    color: 'white',
    fontSize: 20,
    fontWeight: '800',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  moreOptionsContent: {
    backgroundColor: COLORS.primary,
    borderRadius: 15,
    padding: 10,
    width: 250,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 24,
  },
  optionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: "flex-start",
    paddingLeft: 20,
    paddingVertical: 12,
  },
  optionIcon: {
    width: 28,
    marginRight: 10,
  },
  optionText: {
    fontSize: 16,
    color: 'white',
    fontWeight: '600',
    fontFamily: 'Montserrat-SemiBold',
  },
  optionDivider: {
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.2)',
    marginVertical: 5,
    marginHorizontal: 10,
  },
});
