import { StyleSheet } from 'react-native';
import { COLORS } from '../../constants/colors';
import { TYPOGRAPHY } from '../../constants/typography';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    padding: 20,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 20,
  },
  headerActions: {
    flexDirection: 'row',
    gap: 10,
  },
  breadcrumb: {
    ...TYPOGRAPHY.montserrat.regular,
    fontSize: 12,
    color: COLORS.greyText,
    marginBottom: 4,
  },
  title: {
    ...TYPOGRAPHY.montserrat.bold,
    fontSize: 24,
    color: COLORS.black,
  },
  actionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
    gap: 8,
  },
  actionBtnText: {
    ...TYPOGRAPHY.montserrat.bold,
    fontSize: 12,
    color: '#fff',
  },
  exportBtn: { backgroundColor: COLORS.posGreen },
  importBtn: { backgroundColor: COLORS.primary },
  deleteBtn: { backgroundColor: COLORS.posRed },
  trackerContainer: {
    backgroundColor: '#f8f9fa',
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#e9ecef',
  },
  trackerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    alignItems: 'center',
  },
  trackerLabel: {
    ...TYPOGRAPHY.montserrat.bold,
    fontSize: 14,
    color: COLORS.black,
  },
  trackerStatus: {
    ...TYPOGRAPHY.montserrat.medium,
    fontSize: 12,
    color: COLORS.greyText,
  },
  progressBarBg: {
    height: 8,
    backgroundColor: '#dee2e6',
    borderRadius: 4,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: COLORS.primary,
    borderRadius: 4,
  },
  limitWarning: {
    ...TYPOGRAPHY.montserrat.medium,
    fontSize: 12,
    color: COLORS.posRed,
    marginTop: 8,
    textAlign: 'center',
  },
  filtersPlaceholder: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f0f4f7',
    padding: 12,
    borderRadius: 12,
    marginBottom: 20,
    gap: 10,
  },
  filterPlaceholderText: {
    ...TYPOGRAPHY.montserrat.medium,
    fontSize: 13,
    color: COLORS.primary,
  },
  salesList: {
    flex: 1,
  },
  saleItem: {
    backgroundColor: '#fff',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#f1f3f5',
    marginBottom: 12,
    overflow: 'hidden',
  },
  saleRowHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 15,
  },
  saleMainInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 15,
  },
  idCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.primary + '10',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.primary + '30',
  },
  idText: {
    ...TYPOGRAPHY.montserrat.bold,
    color: COLORS.primary,
    fontSize: 14,
  },
  saleTitle: {
    ...TYPOGRAPHY.montserrat.bold,
    fontSize: 16,
    color: COLORS.black,
  },
  saleSubtitle: {
    ...TYPOGRAPHY.montserrat.regular,
    fontSize: 12,
    color: COLORS.greyText,
  },
  saleRightInfo: {
    alignItems: 'flex-end',
    gap: 4,
  },
  saleAmount: {
    ...TYPOGRAPHY.montserrat.bold,
    fontSize: 18,
    color: COLORS.black,
  },
  expandedContent: {
    padding: 15,
    paddingTop: 0,
  },
  divider: {
    height: 1,
    backgroundColor: '#f1f3f5',
    marginBottom: 15,
  },
  itemsLabel: {
    ...TYPOGRAPHY.montserrat.semiBold,
    fontSize: 13,
    color: COLORS.greyText,
    marginBottom: 8,
  },
  productRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  productName: {
    flex: 2,
    ...TYPOGRAPHY.montserrat.medium,
    fontSize: 14,
    color: '#495057',
  },
  productDetails: {
    flex: 1,
    ...TYPOGRAPHY.montserrat.regular,
    fontSize: 12,
    color: COLORS.greyText,
    textAlign: 'center',
  },
  productTotal: {
    flex: 1,
    ...TYPOGRAPHY.montserrat.semiBold,
    fontSize: 14,
    color: COLORS.black,
    textAlign: 'right',
  },
  actionButtonsRow: {
    flexDirection: 'row',
    marginTop: 20,
    gap: 12,
  },
  syncBtn: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: COLORS.primary,
    height: 44,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
  },
  syncBtnText: {
    ...TYPOGRAPHY.montserrat.bold,
    color: '#fff',
    fontSize: 14,
  },
  inlineDeleteBtn: {
    flexDirection: 'row',
    height: 44,
    borderRadius: 10,
    paddingHorizontal: 15,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.posRed + '30',
    gap: 8,
  },
  inlineDeleteText: {
    ...TYPOGRAPHY.montserrat.bold,
    color: COLORS.posRed,
    fontSize: 14,
  },
  emptyContainer: {
    padding: 80,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyTitle: {
    ...TYPOGRAPHY.montserrat.bold,
    fontSize: 20,
    color: COLORS.black,
    marginTop: 20,
  },
  emptySubtitle: {
    ...TYPOGRAPHY.montserrat.medium,
    fontSize: 14,
    color: COLORS.greyText,
    textAlign: 'center',
    marginTop: 8,
  },
  overlayLoader: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255,255,255,0.7)',
    zIndex: 10,
    justifyContent: 'center',
    alignItems: 'center',
  }
});
