export const API_ENDPOINTS = {
  SUPER_ADMIN: "https://basit.ownersanalytics.com/api/posclients",
  AUTH: {
    LOGIN: "/api/login",
    LOGOUT: "/api/logout",
  },
  SETTINGS: {
    SOFTWARE: "/api/softwaresetting",
    LEADS: "/api/leadssetting",
  },
  SHIFT: {
    OPEN: "/api/storeshift",
    CLOSE: "/api/closeshift",
    DETAILS: "/api/registerDetails",
    DAILY_REPORTS: "/api/dailycashreport",
    POS_OPTIONS: "/api/myPosidOption",
    SALES_MAN: "/api/saleman",
  },
  CATALOG: {
    STORES: "/api/mystoreoption",
    CASH_ACCOUNTS: "/api/cashaccount",
    BANK_ACCOUNTS: "/api/bankaccount",
    CREDIT_CARD_ACCOUNTS: "/api/creditcardaccount",
    CUSTOMERS: "/api/customer",
    ACCOUNT_HEADS: "/api/posexpansehead",
    EXPENSE_ACCOUNTS: "/api/posexpanseaccount",
    PO_LIST: "/api/get-po-list",
    POS_CATEGORY: "/api/POScategory",
    SALESLIST: "/api/saleslist",
    DRAFT_SALES_LIST: "/api/draftsaleslist",
    VALIDATE_COUPON: "/api/validatecoupon",
    KITCHEN_ORDERS: "/api/get-kitchen-orders",
    PRODUCTS_POS: "/api/productsPOS",
  },
  TRANSACTIONS: {
    PAID_IN_OUT: "/api/paidin_paidout",
    ADD_EXPENSE: "/api/addposexpanse",
    GENERATE_COUPON: "/api/storecoupon",
    VALIDATE_COUPON: "/api/validatecoupon",
    UPDATE_DEFAULTS: "/api/updatedefaultaccounts",
    UPDATE_CASH_ACCOUNT: "/api/updatecashaccount",
    UPDATE_SALESMAN: "/api/updatesaleman",
  },
  POS: {
    PRODUCTS: "/api/productsPOS",
    CHECKOUT: "/api/cashsale",
    PARTIAL_SALE: "/api/partial-sale",
    QUOTATION: "/api/create_quotation",
    DRAFT_SALE: "/api/draftsale",
    PRINT_BILL: "/api/print_bill",
    UPDATE_SALE: "/api/updatesale",
    GET_INVOICE: "/api/get_invoice",
    UPDATE_KITCHEN_ORDER: "/api/update-order-status",
  }
};
