export const APP_CONSTANTS = {
  appTitle: 'Owners Inventory',
  name: "Name",
  xAxis: "X-axis",
  yAxis: "Y-axis",
  height: "Height",
  width: "Width",
  rotation: "Rotation",
  round: "Round",
  chairs: "Chairs",
  floor: "Floor",
  decoration: "Leaf",
  bookingCapacity: "Capacity",
  table: "Table",
  cancel: "Cancel",
  save: "Save",
  edit: "Edit",
  addFloorTip: "Add New Floor",
  removeFloorTip: "Remove Last Floor",
  addTableTip: "Add New Table",
  removeTableTip: "Remove Current Table",
  addChairTip: "Add New Chair",
  removeChairTip: "Remove Chair",
  increaseHeightTip: "Increase Height",
  decreaseHeightTip: "Decrease Height",
  increaseWidthTip: "Increase Width",
  decreaseWidth: "Decrease Width",
  decreaseXAxisTip: "Decrease X-axis",
  increaseXAxisTip: "Increase X-axis",
  decreaseYAxisTip: "Decrease Y-axis",
  increaseYAxisTip: "Increase Y-axis",
  addLeafTip: "Add New Leaf",
  removeLeafTip: "Remove Current Leaf",
  cancelTip: "Discard Changes",
  saveTip: "Save Changes",
  currentFloorTip: "Current Floor",
};

export const LAYOUT = {
  borderRadius: 15,
  cardRadius: 15,
  buttonRadius: 10,
  padding: 16,
  margin: 16,
};
