import { StyleSheet } from 'react-native';
import { COLORS } from '../../constants/colors';
import { TYPOGRAPHY } from '../../constants/typography';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  loaderContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  loaderText: {
    ...TYPOGRAPHY.montserrat.medium,
    marginTop: 10,
    color: COLORS.greyText,
  },
  header: {
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  backBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  backText: {
    ...TYPOGRAPHY.montserrat.medium,
    fontSize: 16,
    marginLeft: 10,
    color: '#646464',
  },
  titleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 5,
  },
  title: {
    ...TYPOGRAPHY.montserrat.bold,
    fontSize: 24,
    color: COLORS.textDark,
  },
  customerName: {
    ...TYPOGRAPHY.montserrat.bold,
    fontSize: 20,
    color: COLORS.textDark,
  },
  infoRow: {
    alignItems: 'flex-end',
  },
  infoText: {
    ...TYPOGRAPHY.montserrat.medium,
    fontSize: 14,
    color: COLORS.textDark,
  },
  content: {
    padding: 20,
    width: '100%',
  },
  tableBlock: {
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 8,
    overflow: 'hidden',
    width: '100%',
  },
  tableHeaderRow: {
    flexDirection: 'row',
    backgroundColor: COLORS.primary,
    paddingVertical: 10,
    paddingHorizontal: 15,
    alignItems: 'center',
    width: '100%',
    gap: 10,
  },
  columnHeader: {
    ...TYPOGRAPHY.montserrat.bold,
    fontSize: 12,
    color: 'white',
  },
  tableRow: {
    flexDirection: 'row',
    paddingVertical: 12,
    paddingHorizontal: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
    alignItems: 'center',
    backgroundColor: 'rgba(106, 27, 154, 0.05)',
    width: '100%',
    gap: 10,
  },
  returnRow: {
    backgroundColor: 'white',
  },
  cellText: {
    ...TYPOGRAPHY.montserrat.semiBold,
    fontSize: 13,
    color: '#4B5C69',
  },
  cellInput: {
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 4,
    paddingHorizontal: 5,
    paddingVertical: 2,
    fontSize: 13,
    color: COLORS.textDark,
  },
  cellPickerBtn: {
    height: 38,
    borderRadius: 6,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  qtyControl: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 4,
    paddingHorizontal: 5,
    backgroundColor: 'white',
  },
  qtyText: {
    ...TYPOGRAPHY.montserrat.bold,
    fontSize: 13,
    color: COLORS.greyText,
    marginHorizontal: 8,
  },
  statusBadge: {
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  statusBadgeText: {
    ...TYPOGRAPHY.montserrat.bold,
    fontSize: 10,
    color: 'white',
  },
  searchRow: {
    flexDirection: 'row',
    padding: 10,
    alignItems: 'center',
  },
  skuInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 4,
    height: 36,
    paddingHorizontal: 10,
    ...TYPOGRAPHY.montserrat.medium,
    fontSize: 12,
    color: COLORS.textDark,
  },
  searchIconBtn: {
    backgroundColor: COLORS.primary,
    width: 36,
    height: 36,
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 5,
  },
  totalsContainer: {
    marginTop: 20,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 8,
    overflow: 'hidden',
  },
  totalsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: COLORS.primary,
    padding: 12,
  },
  totalsHeaderText: {
    ...TYPOGRAPHY.montserrat.bold,
    fontSize: 14,
    color: 'white',
  },
  totalsBody: {
    padding: 15,
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  totalLabel: {
    ...TYPOGRAPHY.montserrat.medium,
    fontSize: 14,
    color: COLORS.greyText,
  },
  totalValue: {
    ...TYPOGRAPHY.montserrat.medium,
    fontSize: 14,
    color: COLORS.greyText,
  },
  adjustmentInput: {
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
    textAlign: 'right',
    width: 100,
    fontSize: 14,
    color: COLORS.textDark,
  },
  notesSection: {
    marginTop: 20,
  },
  sectionTitle: {
    ...TYPOGRAPHY.montserrat.bold,
    fontSize: 16,
    color: COLORS.textDark,
    marginBottom: 8,
  },
  notesInput: {
    borderWidth: 1,
    borderColor: COLORS.primary,
    borderRadius: 8,
    padding: 12,
    height: 80,
    textAlignVertical: 'top',
    ...TYPOGRAPHY.montserrat.medium,
    fontSize: 14,
    color: COLORS.textDark,
  },
  footerActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
    gap: 10,
  },
  advanceBtn: {
    backgroundColor: COLORS.posRed,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    flex: 1,
    alignItems: 'center',
  },
  advanceBtnText: {
    ...TYPOGRAPHY.montserrat.bold,
    color: 'white',
    fontSize: 14,
  },
  updateBtn: {
    backgroundColor: COLORS.primary,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    flex: 1,
    alignItems: 'center',
  },
  updateBtnText: {
    ...TYPOGRAPHY.montserrat.bold,
    color: 'white',
    fontSize: 14,
  },
  transactionsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 30,
  },
  methodButtonContainer: {
    width: 160,
  },
  methodPickerBtn: {
    height: 44,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.primary,
  },
  validateBtn: {
    backgroundColor: COLORS.primary,
    borderRadius: 4,
    width: 28,
    height: 28,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
