import { StyleSheet } from 'react-native';
import { TYPOGRAPHY } from '../../constants/typography';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F0F2F5' },
  header: {
    height: 70,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    backgroundColor: 'white',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    zIndex: 100
  },
  backButton: { flexDirection: 'row', alignItems: 'center', width: 120 },
  backCirc: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#F7FAFC', justifyContent: 'center', alignItems: 'center', marginRight: 10 },
  backText: { ...TYPOGRAPHY.montserrat.semiBold, fontSize: 13, color: '#4A5568' },
  headerTitle: { flex: 1, textAlign: 'center', ...TYPOGRAPHY.montserrat.bold, fontSize: 18, color: '#1A202C' },
  headerActions: { width: 120, alignItems: 'flex-end' },
  mainContent: { flex: 1, flexDirection: 'row' },
  sidebarSolid: { width: 280, backgroundColor: '#2D1F5C' },
  properCard: { backgroundColor: '#3C2A7D', borderRadius: 16, marginHorizontal: 15, marginTop: 15, padding: 15, borderWidth: 1, borderColor: '#4E3B94' },
  properCardHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  iconCircle: { width: 28, height: 28, borderRadius: 14, backgroundColor: '#4E3B94', justifyContent: 'center', alignItems: 'center', marginRight: 10 },
  properCardTitle: { color: 'white', ...TYPOGRAPHY.montserrat.bold, fontSize: 12, textTransform: 'uppercase', letterSpacing: 0.8 },
  properCardContent: {},
  properRow: { marginBottom: 15 },
  properLabel: { ...TYPOGRAPHY.montserrat.medium, fontSize: 11, color: '#A0AEC0', marginBottom: 5 },
  properInput: { backgroundColor: '#4E3B94', borderRadius: 10, paddingHorizontal: 12, paddingVertical: 10, color: 'white', ...TYPOGRAPHY.montserrat.semiBold, fontSize: 14 },
  flexRow: { flexDirection: 'row', gap: 10 },
  sep: { height: 5 },
  spreadRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  badgeContainer: { backgroundColor: '#2D1F5C', borderRadius: 8, paddingHorizontal: 10, paddingVertical: 6, alignSelf: 'flex-start' },
  badgeText: { color: '#FFD700', ...TYPOGRAPHY.montserrat.bold, fontSize: 12 },
  properToggle: { flexDirection: 'row', backgroundColor: '#2D1F5C', borderRadius: 10, padding: 4 },
  toggBtn: { flex: 1, paddingVertical: 8, alignItems: 'center', borderRadius: 8 },
  toggBtnActive: { backgroundColor: 'white' },
  toggText: { color: '#A0AEC0', ...TYPOGRAPHY.montserrat.bold, fontSize: 11 },
  toggTextActive: { color: '#2D1F5C' },
  counterRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 20 },
  circBtn: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#6750A4', justifyContent: 'center', alignItems: 'center' },
  countNum: { color: 'white', ...TYPOGRAPHY.montserrat.bold, fontSize: 22 },
  quickGrid: { flexDirection: 'row', gap: 10 },
  gridBtn: { flex: 1, backgroundColor: '#4E3B94', padding: 15, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  gridBtnText: { color: 'white', ...TYPOGRAPHY.montserrat.bold, fontSize: 11, marginTop: 5 },
  properEmpty: { margin: 20, alignItems: 'center', padding: 25 },
  properEmptyText: { color: '#A0AEC0', ...TYPOGRAPHY.montserrat.medium, fontSize: 11, textAlign: 'center', marginTop: 10 },
  subText: { color: 'white', ...TYPOGRAPHY.montserrat.medium, fontSize: 12, marginBottom: 5 },
  properCanvas: { flex: 1, padding: 20 },
  properFloor: { flex: 1, backgroundColor: 'white', borderRadius: 20, borderWidth: 1, borderColor: '#1d7af3ff', overflow: 'hidden', shadowColor: '#000', shadowOffset: { width: 0, height: 4 } },
  tableContainer: { position: 'absolute', backgroundColor: '#C1873F', justifyContent: 'center', alignItems: 'center', elevation: 5, shadowColor: '#000', shadowOffset: { width: 0, height: 4 } },
  tableText: { ...TYPOGRAPHY.montserrat.bold, fontSize: 11, color: 'rgba(0,0,0,0.8)', textAlign: 'center' },
  resizeHandle: { position: 'absolute', right: -10, bottom: -10, width: 24, height: 24, backgroundColor: '#6750A4', borderRadius: 12, justifyContent: 'center', alignItems: 'center', zIndex: 100 },

  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  statusModalContent: {
    width: 320,
    backgroundColor: 'white',
    borderRadius: 30,
    padding: 30,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25,
    shadowRadius: 15,
    elevation: 10,
  },
  iconCircLarge: {
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    ...TYPOGRAPHY.montserrat.bold,
    fontSize: 20,
    color: '#2D3748',
    textAlign: 'center',
    marginBottom: 10,
  },
  modalMessage: {
    ...TYPOGRAPHY.montserrat.medium,
    fontSize: 14,
    color: '#718096',
    textAlign: 'center',
    marginBottom: 25,
  },
  modalCloseBtn: {
    width: '100%',
    paddingVertical: 15,
    borderRadius: 15,
    alignItems: 'center',
  },
  modalCloseBtnText: {
    color: 'white',
    ...TYPOGRAPHY.montserrat.bold,
    fontSize: 14,
  },
  modalActionRow: {
    flexDirection: 'row',
    gap: 12,
    width: '100%',
  },
  modalBtnHalf: {
    flex: 1,
    paddingVertical: 15,
    borderRadius: 15,
    alignItems: 'center',
  },
});
