import { StyleSheet } from 'react-native';
import { COLORS } from '../../constants/colors';
import { TYPOGRAPHY } from '../../constants/typography';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    padding: 40,
  },
  loadingText: {
    ...TYPOGRAPHY.montserrat.medium,
    marginTop: 16,
    color: COLORS.greyText,
  },
  errorText: {
    ...TYPOGRAPHY.montserrat.bold,
    marginTop: 16,
    fontSize: 18,
    color: COLORS.textDark,
  },
  errorSubtitle: {
    ...TYPOGRAPHY.montserrat.medium,
    marginTop: 8,
    fontSize: 14,
    color: COLORS.greyText,
    textAlign: 'center',
    paddingHorizontal: 20,
  },
  header: {
    backgroundColor: 'white',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    elevation: 2,
    zIndex: 10,
    width: '100%',
  },
  headerInner: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 20,
    width: '100%',
  },
  backBtn: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#F1F5F9',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  headerInfo: {
    flex: 1,
  },
  title: {
    ...TYPOGRAPHY.montserrat.bold,
    fontSize: 22,
    color: '#1E293B',
  },
  subtitle: {
    ...TYPOGRAPHY.montserrat.medium,
    fontSize: 12,
    color: '#64748B',
    marginTop: 2,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 60,
  },
  infoBar: {
    backgroundColor: 'white',
    padding: 16,
    borderRadius: 15,
    marginBottom: 20,
    gap: 16,
    flexDirection: 'column',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  infoBarTablet: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  infoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  infoIconBox: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: '#F1F5F9',
    justifyContent: 'center',
    alignItems: 'center',
  },
  infoLabel: {
    ...TYPOGRAPHY.montserrat.medium,
    fontSize: 11,
    color: '#64748B',
    textTransform: 'uppercase',
  },
  infoValue: {
    ...TYPOGRAPHY.montserrat.bold,
    fontSize: 14,
    color: COLORS.textDark,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 20,
  },
  statsGridTablet: {
    flexWrap: 'nowrap',
  },
  statCardWrapper: {
    flexGrow: 1,
  },
  statCard: {
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 1,
    borderColor: '#F1F5F9',
    overflow: 'hidden',
  },
  statIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: '#F8FAFC',
    justifyContent: 'center',
    alignItems: 'center',
  },
  statContent: {
    flex: 1,
  },
  statLabel: {
    ...TYPOGRAPHY.montserrat.bold,
    fontSize: 12,
    color: '#64748B',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 4,
  },
  statValue: {
    ...TYPOGRAPHY.montserrat.bold,
    fontSize: 24,
  },
  statWatermark: {
    position: 'absolute',
    right: -5,
    bottom: -5,
    transform: [{ rotate: '15deg' }],
  },
  tablesGrid: {
    flexDirection: 'column',
    gap: 16,
    marginBottom: 24,
  },
  tablesGridTablet: {
    flexDirection: 'row',
  },
  tableContainer: {
    flex: 1,
    backgroundColor: 'white',
    borderRadius: 15,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  tableHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#F1F5F9',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  tableHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  tableHeaderIconBox: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 2,
  },
  tableTitle: {
    ...TYPOGRAPHY.montserrat.bold,
    fontSize: 16,
    color: '#1E293B',
    letterSpacing: 0.5,
  },
  tableTotal: {
    ...TYPOGRAPHY.montserrat.bold,
    fontSize: 17,
    color: COLORS.primary,
  },
  tableBody: {
    padding: 18,
    gap: 14,
  },
  tableRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  rowLead: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  rowLabel: {
    ...TYPOGRAPHY.montserrat.bold,
    fontSize: 13,
    color: '#64748B',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  rowValue: {
    ...TYPOGRAPHY.montserrat.bold,
    fontSize: 14,
    color: COLORS.textDark,
  },
  financialSection: {
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 15,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 4,
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  sectionHeading: {
    ...TYPOGRAPHY.montserrat.bold,
    fontSize: 14,
    color: '#64748B',
    marginBottom: 20,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  financeGrid: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  financeItem: {
    flex: 1,
    alignItems: 'center',
  },
  financeLabel: {
    ...TYPOGRAPHY.montserrat.medium,
    fontSize: 12,
    color: '#64748B',
    marginBottom: 6,
    textAlign: 'center',
  },
  financeValue: {
    ...TYPOGRAPHY.montserrat.bold,
    fontSize: 15,
    color: COLORS.textDark,
  },
  financeGridMobile: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 20,
  },
  financeDivider: {
    width: 1.5,
    height: 40,
    backgroundColor: '#F1F5F9',
  },
  separator: {
    height: 1.5,
    backgroundColor: '#F1F5F9',
    marginVertical: 20,
    marginHorizontal: 10,
  },
  cashFlowSection: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    marginBottom: 32,
    backgroundColor: 'white',
    padding: 24,
    borderRadius: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  cashFlowItem: {
    flex: 1,
    alignItems: 'center',
  },
  cashFlowLabel: {
    ...TYPOGRAPHY.montserrat.medium,
    fontSize: 13,
    color: '#64748B',
    marginBottom: 4,
  },
  cashFlowValue: {
    ...TYPOGRAPHY.montserrat.bold,
    fontSize: 18,
  },
  cashFlowSectionMobile: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  cashFlowDivider: {
    width: 1.5,
    height: 45,
    backgroundColor: '#F1F5F9',
  },
  actionsBox: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 10,
  },
  actionsBoxTablet: {
    justifyContent: 'center',
    flexWrap: 'nowrap',
  },
});
